name: demo_isp_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.5
  build_runner: ^2.4.15
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.0
  get_it: ^8.0.3
  # connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/iconsImg/
